//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 UAS.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UAS_DIALOG                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DLG_NETSET                  129
#define IDD_DLG_INVITE                  130
#define IDD_DLG_PTZ                     131
#define IDD_DLG_CODERSET                132
#define IDD_DLG_ALARM                   133
#define IDD_DLG_TESTMEMBER              134
#define IDD_DLG_LOG                     135
#define IDD_DLG_PLAYER                  136
#define IDD_DLG_VIDEOQUERY              138
#define IDD_DLG_VIDEOPLAY               139
#define IDB_BITMAP1                     140
#define IDD_DLG_CATALOGUREQUERY         141
#define IDD_DLG_DEVICEINFQUERY          142
#define IDD_DLG_FLOWQUERY               143
#define IDD_EQUAL                       144
#define IDC_COMBO1                      1000
#define IDC_BTN_SET                     1001
#define IDC_BTN_OPEN_SIP                1002
#define IDC_BTN_LOG                     1003
#define IDC_BTN_RESULT                  1004
#define IDC_TAB                         1005
#define IDC_BTN_SEND_CLEAR              1006
#define IDC_EDT_SENDMSG                 1007
#define IDC_BTN_RECV_CLEAR              1008
#define IDC_EDT_RECV_MSG                1009
#define IDC_STR_LOCALIP                 1010
#define IDC_STR_LOCAL_PORT              1011
#define IDC_STR_LOCAL_ADD               1012
#define IDC_STR_LOCAL_NAME              1013
#define IDC_STR_REMOTE_IP               1014
#define IDC_STR_REMOTE_PORT             1015
#define IDC_STR_REMOTE_ADD              1016
#define IDC_STR_REMOTE_NAME             1017
#define IDC_EDT_ADDRESS                 1018
#define IDC_EDT_SENDMSG2                1018
#define IDC_IP                          1019
#define IDC_EDT_PORT                    1020
#define IDC_EDT_NAME                    1021
#define IDC_BTN_ALTER                   1022
#define IDC_EDT_USERCODE                1023
#define IDC_EDT_FORMAT                  1024
#define IDC_EDT_AUDIO                   1025
#define IDC_EDT_VIDEO                   1026
#define IDC_EDT_MAXBIT                  1027
#define IDC_EDT_TRANSMODE               1028
#define IDC_EDT_MULTICAST               1029
#define IDC_EDT_PROTOCOL                1030
#define IDC_EDT_SOCKET                  1031
#define IDC_EDT_TRANSMODE2              1032
#define IDC_BTN_TEST                    1033
#define IDC_BTN_PRE                     1034
#define IDC_EDT_PTZ                     1035
#define IDC_EDT_ADD                     1036
#define IDC_EDT_PTL                     1037
#define IDC_EDT_FRAME                   1041
#define IDC_EDT_BITRATE                 1042
#define IDC_EDT_PRIORITY                1043
#define IDC_EDT_GOP                     1044
#define IDC_EDT_LEVEL                   1047
#define IDC_BTN_ALARM_SET               1048
#define IDC_EDT_IP                      1049
#define IDC_EDT_ADDNAME                 1049
#define IDC_BTN_ADD                     1050
#define IDC_BTN_ALARM_SET2              1050
#define IDC_BTN_TIMESET                 1050
#define IDC_EDT_IP2                     1050
#define IDC_EDT_ALTERNAME               1051
#define IDC_BTN_ALARM_SET3              1051
#define IDC_BTN_ALARM_CANCEL            1051
#define IDC_EDT_ALARM_TYPE              1052
#define IDC_EDT_MEMBERIP                1052
#define IDC_BTN_DELETE                  1053
#define IDC_BOX_LIST                    1054
#define IDC_STR_COUNT                   1055
#define IDC_BTN_REFRESH                 1056
#define IDC_EDT_MEMBERIPADD             1056
#define IDC_EDT_LOG                     1057
#define IDC_BTN_BYE                     1058
#define IDC_BTN_PLAY                    1059
#define IDC_EDT_URL                     1060
#define IDC_BTN_CANCEL                  1060
#define IDC_VLCPLAY                     1061
#define IDC_BTN_PLAY2                   1061
#define IDC_STR_URL                     1063
#define IDC_EDT_PRIVILEGE               1065
#define IDC_EDT_FILETYPE                1066
#define IDC_EDT_MAXFILENUM              1067
#define IDC_EDT_ENDTIME                 1068
#define IDC_EDT_BEGINTIME               1069
#define IDC_EDT_FILESIZE                1070
#define IDC_EDT_REALNUM                 1071
#define IDC_EDT_END                     1072
#define IDC_EDT_BEGIN                   1073
#define IDC_COMBO_LIST                  1074
#define IDC_EDT_MAXFILENUM2             1075
#define IDC_EDT_DESTINATION             1077
#define IDC_EDT_CLIENTPORT              1078
#define IDC_EDT_RANGE                   1079
#define IDC_EDT_SCALE                   1080
#define IDC_BTN_START                   1081
#define IDC_BTN_QUERY                   1082
#define IDC_BTN_STOP                    1083
#define IDC_BTN_GETURL                  1083
#define IDC_STATICPIC                   1083
#define IDC_SABOUT                      1084
#define IDC_STATICMT                    1085
#define IDC_QUERY                       1086
#define IDC_DEVICEINFQUERY              1087
#define IDC_FLOWQUERY                   1088
#define IDC_DEVICEINFQUERY2             1088
#define IDC_EDT_BEGINNUM                1091
#define IDC_EDT_ENDNUM                  1092
#define IDC_REGSITERE                   1093
#define IDC_NOTIFYE                     1094
#define IDC_IPE                         1095
#define IDC_EDT_PORTE                   1096
#define IDC_EDT_ADDRESSE                1097
#define IDC_EDT_NAMEE                   1098
#define IDC_USERNAMES                   1099
#define IDC_EDIT2                       1100
#define IDC_PASSWORDS                   1100
#define IDC_EDIT_DEVICEINFO             1100
#define IDC_EDIT_NOTEINFO               1100
#define IDC_SUBNOTE                     1101
#define IDC_SELADRESS                   1102
#define IDC_CHECK1                      1103
#define IDC_PTZUP                       1104
#define IDC_SELADRESS2                  1104
#define IDC_SELalarmtype                1104
#define IDC_PTZLEFT                     1105
#define IDC_BUTTON1                     1105
#define IDC_BUTTON_REBOOT               1105
#define IDC_PZTDOWN                     1106
#define IDC_COMBO2                      1106
#define IDC_COMBO_IP                    1106
#define IDC_PTZRIGHT                    1107
#define IDC_EDIT1                       1107
#define IDC_EDIT_IMAGEQUALITY           1107
#define IDC_PTZUP2                      1108
#define IDC_EDIT_FLOWQUERY              1108
#define IDC_PTZUP3                      1109
#define IDC_PTZUP4                      1110
#define IDC_PTZUP5                      1111
#define IDC_PTZUP6                      1112
#define IDC_PTZUP7                      1113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
