// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vlcplay.h"

/////////////////////////////////////////////////////////////////////////////
// CVlcplay

IMPLEMENT_DYNCREATE(CVlcplay, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVlcplay properties

/////////////////////////////////////////////////////////////////////////////
// CVlcplay operations
